name: Release

on:
    pull_request:
        branches:
            - main
        types:
            - closed

jobs:
    release:
        if: github.event.pull_request.merged == true
        name: Build and Create GitHub Release
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup Poetry
              uses: ./.github/actions/setup-poetry
            - name: Get version from pyproject.toml
              id: get-version
              run: |
                VERSION=$(poetry version -s)
                echo "version=$VERSION" >> $GITHUB_OUTPUT
            - name: Create Git tag
              run: |
                git config user.name "github-actions"
                git config user.email "github-actions@github.com"
                git tag ${{ steps.get-version.outputs.version }}
                git push origin ${{ steps.get-version.outputs.version }}
            - name: Build package
              run: poetry build
            - name: Extract Changelog
              id: extract-changelog
              uses: sean0x42/markdown-extract@v2.1.0
              with:
                file: CHANGELOG.md
                pattern: '${{ steps.get-version.outputs.version }}'
            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                tag_name: ${{ steps.get-version.outputs.version }}
                body: ${{ steps.extract-changelog.outputs.markdown }}
                make_latest: true
                files: |
                    dist/*.whl
                    dist/*.tar.gz
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
